sudo: required

# not necessary, but less confusing if defined
language: python

services:
  - docker

# we do everything in docker for non MacOS, MacOS setup is in .ci/build.sh
install: skip
before_install: skip

stages:
- name: deploy
  if: tag is PRESENT

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo sed -i '1i 127.0.0.1 test.box' /etc/hosts;
  sudo hostname test.box;
  source ./.ci/lib-util.sh;
  util::docker-run $DISTRO ./.ci/build.sh;
  fi
- if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then ./.ci/build.sh; fi

jobs:
  # need to explictly define each builder for test due to different os types
  include:
  - stage: deploy
    script: skip
    env:
    - DISTRO=fedora:latest
    - PYTHON="3"
    - secure: L5SpEj5+no20PWwC9Y/XNhAfmUvYiuykwSMa/YyqvUuBjdizzpZcHr7Ego5nMdM1TniTxj4pSTM+GbM0FHCzNmAINSRh9g/D3hheRqlRBacqR0XwC9ZZRvkKvtzwnLh4vYWiauq4AoDeR5U6tkEcay6LjE57iMQcLjcKYBc+Eos=
    before_deploy:
    - source ./.ci/lib-util.sh
    - util::docker-run $DISTRO ./.ci/before-deploy.sh
    - ls -alR `pwd`

    deploy:
    - provider: releases
      api_key:
        secure: fAaSSSjd/nUrIpINBjAT590pGF2nGq3I8ee6aGq6IAFpXoa/9eeN5eyOrE4MYucWCwYcH28c7510n35vuZQQor+UZIDo6l0K5M64/NZE1cZ43zOMjw3yHlrsJG+ohPS7YvjqD8GaFlLhF6ZvWvrPmWeijvs8qAT1eL7QoEG0xBk=
      file_glob: true
      file:
        - tag_build/*
      skip_cleanup: true
      on:
        all_branches: true

    - provider: pypi
      user: rharwood
      password:
        secure: "hN861mjtLeC8IysypC6Pqzlazq29I+c69XGjbUR53izYQ90cz2F+B2azVTl9Su9NbXzdsGnhWZrjY1jtYMPIZE15xDaC8vs61QijFClqmyuKNRVzCt1w/sj21hyLXnYIrkAo4e3bswPF+hRGNwfb+rVrR/dqUwd1wyjZBBYMcQE="
      skip_cleanup: true
      docs_dir: travis_docs_build/html
      on:
        all_branches: true
      # NB(directxman12): this is a hack.  Check ./.ci/before-deploy.sh for an explanation.
      distributions: "check"

    - provider: script
      script: .ci/docs-deploy.sh travis_docs_build/html stable pythongssapi/python-gssapi
      skip_cleanup: true
      on:
        all_branches: true

  - &win_deploy
    stage: deploy
    os: windows
    script: # This is egregious hacks around Travis
      - ./.ci/before-deploy-windows-wheels.sh
      - ./.ci/deploy-win.sh
    env:
      - PYTHON="3"
      - PYENV="3.8.1"
    language: sh # Travis doesn't support python here

  - <<: *win_deploy
    env:
      - PYTHON="3"
      - PYENV="3.7.3"

  - <<: *win_deploy
    env:
      - PYTHON="3"
      - PYENV="3.6.8"

